name: Testes Automatizados da PokeAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testar:
    name: Executar testes de API
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v4

      - name: ☕ Instalar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 📦 Instalar dependências e rodar testes
        run: mvn clean test

      - name: 📄 Salvar relatório Extent
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report
          path: target/extent-report.html